# Generated by Django 5.1.8 on 2026-02-20 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='marked_at',
            new_name='first_available_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='current_availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_auto', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
