# Generated by Django 5.2.12 on 2026-05-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_marked_at_attendance_first_available_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesettings',
            name='user_terminology',
            field=models.CharField(choices=[('employee', 'Employee'), ('developer', 'Developer')], default='employee', help_text='Terminology to use for staff (Employee or Developer)', max_length=20),
        ),
    ]
