# Generated by Django 5.1.8 on 2026-03-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
