# Generated by Django 5.2.9 on 2026-02-18 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('holiday', 'Holiday'), ('programme', 'Programme'), ('meeting', 'Meeting'), ('deadline', 'Deadline'), ('birthday', 'Birthday'), ('other', 'Other')], default='other', max_length=20)),
                ('color', models.CharField(default='#6b7280', help_text='Hex color code', max_length=7)),
                ('is_full_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'db_table': 'calendar_events',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date'], name='calendar_ev_date_a999d5_idx'), models.Index(fields=['category'], name='calendar_ev_categor_4b382b_idx')],
            },
        ),
    ]
