# Generated by Django 4.2.30 on 2026-07-14 07:51

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
        migrations.CreateModel(
            name='TenantLoginAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('tenant_user_id', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_accounts', to='customers.client')),
            ],
            options={
                'db_table': 'customers_tenant_login_account',
            },
        ),
        migrations.AddConstraint(
            model_name='tenantloginaccount',
            constraint=models.UniqueConstraint(fields=('client', 'tenant_user_id'), name='customers_login_account_client_user_uniq'),
        ),
    ]
